import { Link } from "@tanstack/react-router";
import { Menu, Phone, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { phoneHref, whatsappHref } from "@/lib/contact";

const nav = [["Vehicles", "/vehicles"], ["Brands", "/brands"], ["Financing", "/financing"], ["Contact", "/contact"]] as const;
export function BrandMark() { return <Link to="/" className="font-display text-lg font-bold tracking-[0.18em] text-foreground">BERIZU <span className="text-primary">MOTORS</span></Link>; }
export function SiteHeader() { const [open,setOpen]=useState(false); return <header className="fixed inset-x-0 top-0 z-50 border-b border-border/70 bg-background/80 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><BrandMark/><nav className="hidden items-center gap-8 md:flex" aria-label="Main navigation">{nav.map(([label,to])=><Link key={to} to={to} className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground transition-colors hover:text-foreground" activeProps={{className:"text-foreground"}}>{label}</Link>)}</nav><div className="hidden md:block"><Button variant="accent" asChild><a href={whatsappHref("Hello Berizu Motors, I would like to enquire about a vehicle.")} target="_blank" rel="noreferrer">Enquire now</a></Button></div><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="border-t border-border bg-background px-5 py-5 md:hidden">{nav.map(([label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="block border-b border-border py-4 text-sm font-semibold uppercase tracking-[0.12em]">{label}</Link>)}</nav>}</header>; }
export function SiteFooter(){return <footer className="border-t border-border bg-surface-deep pb-24 pt-14 md:pb-10"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-3 lg:px-8"><div><BrandMark/><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">Premium vehicles, flexible financing and trusted automotive service in Kisumu, Kenya.</p></div><div><p className="eyebrow">Visit us</p><p className="mt-3 text-sm text-muted-foreground">Kisumu, Kenya</p></div><div className="md:text-right"><a href={phoneHref} className="text-lg font-semibold text-foreground">Call Berizu Motors</a><p className="mt-3 text-xs uppercase tracking-[0.15em] text-muted-foreground">Quality in every journey</p></div></div></footer>}
export function PageShell({children}:{children:ReactNode}){return <><SiteHeader/><main>{children}</main><SiteFooter/><MobileEnquiry/></>}
function MobileEnquiry(){return <div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 gap-px border-t border-border bg-border p-px md:hidden"><Button asChild variant="secondary" className="h-14 rounded-none"><a href={phoneHref}><Phone/>Call</a></Button><Button asChild variant="accent" className="h-14 rounded-none"><a href={whatsappHref("Hello Berizu Motors, I would like to enquire about a vehicle.")} target="_blank" rel="noreferrer">WhatsApp</a></Button></div>}
