import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Bot, Building2, Headphones, MapPin, MessageCircle, Phone, Search, ShieldCheck, SlidersHorizontal, Sparkles, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Vehicle } from "@/lib/woocommerce.functions";
import { directionsHref, phoneHref, whatsappHref } from "@/lib/contact";
import { VehicleCard } from "./VehicleCard";
export function SectionHeading({eyebrow,title,detail}:{eyebrow:string;title:string;detail?:string}){return <div className="mb-9 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 font-display text-3xl font-semibold uppercase leading-tight md:text-5xl">{title}</h2></div>{detail&&<p className="max-w-md text-sm leading-6 text-muted-foreground">{detail}</p>}</div>}
export function FeaturedVehicles({vehicles,error}:{vehicles:Vehicle[];error?:string|null}){return <section className="section-space bg-background"><div className="page-wrap"><SectionHeading eyebrow="Curated inventory" title="Featured vehicles" detail="Selected vehicles currently available from our Kisumu showroom."/>{error&&<p className="mb-6 border-l-2 border-primary pl-4 text-sm text-muted-foreground">{error}</p>}<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{vehicles.slice(0,6).map(v=><VehicleCard key={v.id} vehicle={v}/>)}</div><div className="mt-10"><Button asChild variant="outline" size="lg"><Link to="/vehicles">View all vehicles <ArrowRight/></Link></Button></div></div></section>}
const filterOptions=["All","SUVs","Sedans","Pickups","Trucks"];
export function VehicleFilters({vehicles}:{vehicles:Vehicle[]}){const [type,setType]=useState("All");const [query,setQuery]=useState("");const filtered=useMemo(()=>vehicles.filter(v=>(type==="All"||v.categories.some(c=>c.name.toLowerCase().includes(type.slice(0,-1).toLowerCase())))&&v.name.toLowerCase().includes(query.toLowerCase())),[vehicles,type,query]);return <section className="section-space bg-surface-deep"><div className="page-wrap"><SectionHeading eyebrow="Find your vehicle" title="Built around your drive" detail="Search our live inventory by vehicle type, brand or model."/><div className="mb-8 grid gap-4 border-y border-border py-6 lg:grid-cols-[1fr_auto]"><label className="flex h-12 items-center gap-3 border border-border bg-background px-4"><Search className="size-4 text-primary"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" placeholder="Search make or model"/></label><div className="flex gap-2 overflow-x-auto pb-1">{filterOptions.map(x=><Button key={x} variant={type===x?"accent":"outline"} onClick={()=>setType(x)}>{x}</Button>)}</div></div><div className="mb-6 flex items-center justify-between"><p className="text-sm text-muted-foreground">{filtered.length} vehicles</p><span className="flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-muted-foreground"><SlidersHorizontal className="size-4"/>Live inventory</span></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map(v=><VehicleCard key={v.id} vehicle={v}/>)}</div></div></section>}
export function FinanceCTA(){return <section className="relative overflow-hidden border-y border-border bg-secondary"><div className="absolute inset-y-0 right-0 hidden w-2/5 border-l border-border bg-accent/30 lg:block"/><div className="page-wrap relative grid min-h-[430px] items-center gap-10 py-20 lg:grid-cols-[1.35fr_.65fr]"><div><p className="eyebrow">Berizu financing</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-semibold uppercase leading-[1.05] md:text-6xl">Get behind the wheel sooner.</h2><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Finance your vehicle through our banking partners with financing options of up to 90%.</p><Button asChild variant="accent" size="xl" className="mt-8"><Link to="/financing">Check finance options <ArrowRight/></Link></Button></div><div className="relative hidden justify-self-center lg:block"><div className="grid size-48 place-items-center rounded-full border border-primary/50"><div className="grid size-32 place-items-center rounded-full border border-border font-display text-4xl font-bold text-primary">90%</div></div></div></div></section>}
export function BrandSection({vehicles}:{vehicles:Vehicle[]}){const brands=Array.from(new Set(vehicles.map(v=>v.name.split(" ")[0]).filter((b):b is string=>Boolean(b))));return <section className="section-space bg-background"><div className="page-wrap"><SectionHeading eyebrow="Our marques" title="Brands at Berizu" detail="Current makes are drawn directly from our live vehicle inventory."/><div className="grid grid-cols-2 border-l border-t border-border sm:grid-cols-3 lg:grid-cols-5">{brands.slice(0,10).map(b=><Link key={b} to="/vehicles" search={{brand:b}} className="grid h-32 place-items-center border-b border-r border-border font-display text-xl font-semibold uppercase text-muted-foreground transition-colors hover:bg-secondary hover:text-primary">{b}</Link>)}</div></div></section>}
export function AiSection(){return <section className="section-space border-y border-border bg-ai-grid"><div className="page-wrap flex flex-col items-start justify-between gap-10 md:flex-row md:items-center"><div className="max-w-2xl"><div className="mb-5 flex size-12 items-center justify-center border border-primary/40 bg-primary/10"><Bot className="text-primary"/></div><p className="eyebrow">Berizu AI</p><h2 className="mt-3 font-display text-4xl font-semibold uppercase md:text-5xl">Not sure what to buy?</h2><p className="mt-5 text-muted-foreground">Tell Berizu AI what you need and discover vehicles that match your requirements.</p></div><Button asChild variant="accent" size="xl"><Link to="/contact">Ask Berizu AI <Sparkles/></Link></Button></div></section>}
export function WhyBerizu(){const items=[[ShieldCheck,"Quality Vehicles","Carefully selected vehicles for confident ownership."],[Building2,"Flexible Financing","Up to 90% financing through trusted banking partners."],[Headphones,"Professional Support","Clear guidance from enquiry to handover."],[Wrench,"Trusted Automotive Service","Support that continues beyond the sale."]];return <section className="section-space bg-background"><div className="page-wrap"><SectionHeading eyebrow="The Berizu standard" title="Why Berizu"/><div className="grid border-l border-t border-border md:grid-cols-2 lg:grid-cols-4">{items.map(([Icon,title,text],i)=>{const I=Icon as typeof ShieldCheck;return <div key={String(title)} className="border-b border-r border-border p-7"><span className="mb-12 block font-mono text-xs text-primary">0{i+1}</span><I className="mb-5 size-6 text-primary"/><h3 className="font-display text-lg font-semibold uppercase">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{String(text)}</p></div>})}</div></div></section>}
export function ContactCTA(){return <section className="section-space bg-foreground text-background"><div className="page-wrap"><p className="eyebrow text-primary">Start the conversation</p><h2 className="mt-4 max-w-4xl font-display text-4xl font-semibold uppercase leading-tight md:text-7xl">Ready to find your next vehicle?</h2><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Button asChild variant="accent" size="xl"><a href={whatsappHref("Hello Berizu Motors, I’m looking for my next vehicle.")} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp us</a></Button><Button asChild variant="inverse" size="xl"><a href={phoneHref}><Phone/>Call Berizu Motors</a></Button><Button asChild variant="inverse" size="xl"><a href={directionsHref} target="_blank" rel="noreferrer"><MapPin/>Get directions</a></Button></div></div></section>}
export function WhatsAppCTA({vehicleName}:{vehicleName:string}){return <Button asChild variant="accent" size="xl" className="w-full"><a href={whatsappHref(`Hello Berizu Motors, I’m interested in the ${vehicleName}. Is it available?`)} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp enquiry</a></Button>}
export function VehicleSpecs({vehicle}:{vehicle:Vehicle}){const data=[["Engine",vehicle.attributes["engine"]],["Transmission",vehicle.attributes["transmission"]],["Drive type",vehicle.attributes["drive type"]||vehicle.attributes["drivetrain"]],["Fuel type",vehicle.attributes["fuel type"]||vehicle.attributes["fuel"]],["Mileage",vehicle.attributes["mileage"]],["Condition",vehicle.attributes["condition"]||(vehicle.categories.some(c=>c.slug.includes("used"))?"Used":"Available")]];return <div className="grid grid-cols-2 border-l border-t border-border md:grid-cols-3">{data.map(([k,v])=><div key={k} className="border-b border-r border-border p-5"><p className="text-[10px] uppercase tracking-[0.15em] text-muted-foreground">{k}</p><p className="mt-2 font-semibold">{v||"Contact us"}</p></div>)}</div>}
export function SimilarVehicles({vehicles}:{vehicles:Vehicle[]}){return <section className="section-space bg-surface-deep"><div className="page-wrap"><SectionHeading eyebrow="Keep exploring" title="Similar vehicles"/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{vehicles.slice(0,3).map(v=><VehicleCard key={v.id} vehicle={v}/>)}</div></div></section>}
